import streamlit as st
import pandas as pd
from PIL import Image
import subprocess
import os
import base64
import pickle

########################################
# Molecular descriptor calculation
########################################
def desc_calc():
    # Define absolute paths for PaDEL-Descriptor and descriptor files
    padel_jar = "/Users/muhammadali/PycharmProjects/pythonProject13/PaDEL-Descriptor/PaDEL-Descriptor.jar"
    fingerprint_xml = "/Users/muhammadali/PycharmProjects/pythonProject13/PaDEL-Descriptor/descriptors.xml"
    output_file = "/Users/muhammadali/PycharmProjects/pythonProject13/descriptors_output.csv"
    input_file = "/Users/muhammadali/PycharmProjects/pythonProject13/molecule.smi"

    # Remove old output file if it exists
    if os.path.exists(output_file):
        os.remove(output_file)

    # Construct the command to run PaDEL
    bashCommand = (
        f"java -Xms2G -Xmx2G -Djava.awt.headless=true "
        f"-jar {padel_jar} "
        f"-removesalt -standardizenitro -fingerprints "
        f"-descriptortypes {fingerprint_xml} "
        f"-dir /Users/muhammadali/PycharmProjects/pythonProject13/ "
        f"-file descriptors_output.csv"
    )
    # Run PaDEL-Descriptor
    process = subprocess.Popen(bashCommand.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, error = process.communicate()

    # Debug output
    st.write("PaDEL OUTPUT:", output.decode('utf-8'))
    st.write("PaDEL ERROR:", error.decode('utf-8'))

    # Check if the descriptors output file was created
    if not os.path.exists(output_file):
        st.error("PaDEL failed. Descriptors file not created.")
        st.stop()

    # Remove the temporary molecule.smi file
    if os.path.exists(input_file):
        os.remove(input_file)

########################################
# File download link
########################################
def filedownload(df):
    csv = df.to_csv(index=False)
    b64 = base64.b64encode(csv.encode()).decode()
    href = f'<a href="data:file/csv;base64,{b64}" download="prediction.csv">Download Predictions</a>'
    return href

########################################
# Model predictions
########################################
def build_model(input_data, smiles_list):
    model_file = "/Users/muhammadali/PycharmProjects/pythonProject13/MAOB_model.pkl"
    load_model = pickle.load(open(model_file, 'rb'))
    prediction = load_model.predict(input_data)

    st.header('**Prediction output**')
    df_result = pd.DataFrame({
        'SMILES': smiles_list,
        'pIC50': prediction
    })
    st.write(df_result)
    st.markdown(filedownload(df_result), unsafe_allow_html=True)

########################################
# Streamlit app layout
########################################

st.title("Bioactivity Prediction App (Monoamine Oxidase B)")
image = Image.open('logo.png')
st.image(image, use_column_width=True)
"App built in `Python` + `Streamlit` by [Muhammad Ali and Asad Zahid]"

st.markdown("""
This app predicts the bioactivity (pIC50) towards inhibiting **Monoamine Oxidase B** 
using a pre-trained Random Forest model and molecular descriptors generated by 
[PaDEL-Descriptor](http://www.yapcwsoft.com/dd/padeldescriptor/).
---
""")

# Sidebar - File Upload
with st.sidebar.header('1. Upload your TXT data'):
    uploaded_file = st.sidebar.file_uploader("Upload your input file", type=['txt'])
    st.sidebar.markdown("""**Example format**:"CCOc1ccc(C(=O)NCc2ccccc2)cc1 CHEMBL999 C/C=C\C(=O)Nc1ccc(Br)cc1 CHEMBL123"
(Two columns: the first is SMILES, the second is an ID.)
""")

########################################
# Main prediction process
########################################
if st.sidebar.button('Predict'):
    # Read the uploaded file
    df_input = pd.read_table(uploaded_file, header=None, sep=None, engine='python')

    # Keep only the first column (SMILES)
    df_input = df_input.iloc[:, [0]]
    df_input.columns = ['SMILES']

    # Save input as 'molecule.smi'
    df_input.to_csv('/Users/muhammadali/PycharmProjects/pythonProject13/molecule.smi', sep='\t', header=False, index=False)

    st.subheader('**Original input data**')
    st.write(df_input)

    # Calculate descriptors
    with st.spinner("Calculating descriptors..."):
        desc_calc()

    # Read descriptors
    output_file = "/Users/muhammadali/PycharmProjects/pythonProject13/descriptors_output.csv"
    st.subheader('**Calculated molecular descriptors**')
    if os.path.exists(output_file):
        desc = pd.read_csv(output_file)
        st.write(desc)
        st.write(f"**Descriptors shape:** {desc.shape}")
    else:
        st.error("Descriptors file not found. PaDEL might have failed.")
        st.stop()

    # Subset descriptors for the model
    descriptor_list_file = "/Users/muhammadali/PycharmProjects/pythonProject13/descriptor_list.csv"
    if os.path.exists(descriptor_list_file):
        Xlist = list(pd.read_csv(descriptor_list_file).columns)
        desc_subset = desc[Xlist]
        st.subheader('**Subset of descriptors**')
        st.write(desc_subset)
        st.write(f"**Subset shape:** {desc_subset.shape}")
    else:
        st.error("descriptor_list.csv not found. Please ensure the file is present.")
        st.stop()

    # Predict using the model
    build_model(desc_subset, df_input['SMILES'])

else:
    st.info("Upload a file in the sidebar to begin!")
